# Generated by Django 5.1.1 on 2024-09-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='intro',
            new_name='content',
        ),
    ]
