# Generated by Django 5.1.1 on 2024-09-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_posts_post_category_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
