# Generated by Django 5.1.1 on 2024-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_comment_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
